# GAIA EXECUTION IMITATION
gaia_imitation: True
gaia_kfold_cv_n_splits: 5
gaia_kfold_shuffle: False
gaia_kfold_random_state: null
# set null to get the seed from the clock value, otherwise specify a number
random_seed: 1

# GROUND TRUTH
# the ground truth data directory
ground_truth_directory: acousticbrainz-datasets
# classes with features locally: danceability, gender, genre_rosamerica, moods_claurier, moods_mirex, timbre_bright_dark
# classes with features locally: tonal_atonal, voice_instrumental
# classes with features online: genre_dortmund, genre_electronic, genre_tzanetakis, ismir04_rhythm,
class_dir: danceability
enumeration_columns: ['tonal_chords_key', 'tonal_chords_scale', 'tonal_key_key', 'tonal_key_scale']
# remove the unnecessary DF columns before training (it will also be deleted the class name column)
remove_columns: ['json_directory',  'track']
exports_directory: exports
evaluations_directory: evaluations
tracks_in_csv_format: tracks_csv
delete_logs: True
# logs directory
log_directory: logs
logging_level: 0

## ML SETTINGS
# train kind: grid_svm, svm, deep_learning, supervised_lb
train_kind: svm
svc_C: 7  # C: float, default=1.0
svc_kernel: rbf  # kernel: {‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘precomputed’}, default=’rbf’
svc_gamma: -11  # gamma: {‘scale’, ‘auto’} or float, default=’scale’
svc_class_weight_balance: null  # class_weight: dict or ‘balanced’, default=None
svc_probability: True
# GRID ML SETTINGS
#
pca_n_components: .95
grid_kernel: ['poly', 'rbf']
#grid_C: [0.001, 0.01, 0.1, 1, 3, 5, 7, 9, 10, 11, 100]
#grid_gamma: [0.001, 0.01, 0.1, 1, 3, 5, 7, 9, 10, 11, 100]
grid_C: [-5, -3, -1, 1, 3, 5, 7, 9, 11]  # will actually be 2**x
grid_gamma: [3, 1, -1, -3, -5, -7, -9, -11]  # will actually be 2**x
grid_class_weight: ['balanced', null]
k_fold: 5
# shuffle: True or False
shuffle: True
# set to -1 if you want to exploit all processors. Set to null if you want to exploit only 1 processor
parallel_jobs: -1
grid_results_directory: grid_scores

# NEURAL NETWORK SETTINGS
#
