ground_truth_directory: acousticbrainz-datasets
# classes with features locally: danceability, gender, genre_rosamerica, moods_claurier, moods_mirex, timbre_bright_dark
# classes with features locally: tonal_atonal, voice_instrumental
# classes with features online: genre_dortmund, genre_electronic, genre_tzanetakis, ismir04_rhythm,
class_name_train: voice_instrumental
# train kind: grid_svm, svm, deep_learning, supervised_lb
train_kind: grid_svm
enumeration_columns: ['tonal_chords_key', 'tonal_chords_scale', 'tonal_key_key', 'tonal_key_scale']
# remove the unnecessary DF columns before training (it will also be deleted the class name column)
remove_columns: ['json_directory',  'track']
exports_directory: exports
evaluations_directory: evaluations

# ML SETTINGS
#
pca_n_components: .95
grid_kernel: ['poly', 'rbf']
grid_gamma: [0.001, 0.01, 0.1, 1, 3, 5, 7, 9, 10, 11, 100]
grid_C: [0.001, 0.01, 0.1, 1, 3, 5, 7, 9, 10, 11, 100]
grid_class_weight: ['balanced', null]
k-fold: 5
# set to -1 if you want to exploit all processors. Set to null if you want to exploit only 1 processor
parallel_jobs: null

# NEURAL NETWORK SETTINGS
#